### ISSUE TITLE
jsonrpc process connection error

### ISSUE THREAD

**Issue by ezaquarii** [copilot-emacs/copilot.el#258]
Trying to call any copilot function results in error:

```
Invalid slot name: "#<jsonrpc-process-connection jsonrpc-process-connection-1aa5a44>", :events-buffer-config
```

I'm not sure how to debug the problem. Installed using manual setup procedure.

**Comment by jasalt** [comment]
There's multiple duplicate issues for "Invalid slot name" error resulting from jsonrpc package version mismatch as the built-in version is too old.

- https://github.com/copilot-emacs/copilot.el/issues/257
- https://github.com/copilot-emacs/copilot.el/issues/244
- https://github.com/copilot-emacs/copilot.el/issues/232

Also the readme was updated (https://github.com/copilot-emacs/copilot.el/commit/a06d27a24dd6a90ece41b29be743dd9710df19e8) to include mention about it in "Ensure your Emacs version is at least 27, the dependency package editorconfig (melpa) and jsonrpc (elpa, >= 1.0.24) are both installed.".

However having to manually "pin" packages over built-in package versions this way is not a very usual process and I think it should be better documented and included in a copy-paste starter config so that it would (most probably) work.

**Comment by jasalt** [comment]
Had same problem and got it fixed by searching and selecting `jsonrpc` from `package-list-packages` and clicking install button there.

Couldn't figure out yet how to install it with `use-package` in config, being new to pinning packages like this. The up-to-date jsonrpc 1.0.24 package is in [GNU ELPA](https://elpa.gnu.org/packages/jsonrpc.html). Tried following that did not have effect:

```
(use-package jsonrpc :ensure t :pin gnu)  ; GNU ELPA install
```
There was also some weird network issue with that for a moment might have affected..

Package it's also mirrored in https://github.com/emacs-straight/jsonrpc/, so I tried install with straight:

```
(use-package jsonrpc
:straight (:type git :host github :repo "emacs-straight/jsonrpc" :files ("*" (:exclude ".git")))
:ensure t)
```

It cloned repo in `~/.emacs.d/straight/repos` and built it to `~/.emacs.d/straight/build`, but emacs doesn't seem to load those over built-in version and same error messages remained.

Emacs installed from Debian [Bookworm Backports](https://packages.debian.org/bookworm-backports/emacs), `version`: `GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.37, cairo version 1.16.0) of 2023-09-11, modified by Debian`, jsonrpc 1.0.16.
